#!/bin/bash
OUT="object.bin"
cd selfex/payload
tar cf ../../payload.tar ./*
cd ../..
if [ -e "payload.tar" ]; then
	gzip payload.tar
	if [ -e "payload.tar.gz" ]; then
		cat selfex/decompress payload.tar.gz > $OUT
	else 
		echo "payload.tar.gz does not exist" 
		exit 1
	fi
else 
	echo "payload.tar does not exist"
	exit 1
fi
rm payload.tar.gz
echo "$OUT created"
exit 0
